--!strict
-- FICHIER GÉNÉRÉ par tools/terrain.js : ne pas modifier à la main (relancer : node tools/terrain.js).
-- Terrain de chaque région (voir Config/Terrain) et rivières entre régions voisines par la terre :
-- rivers["A|B"] (A avant B dans l'ordre alphabétique) = "Riviere" ou "Fleuve".

local RegionTerrain = {
	terrain = {
		AFG = "Montagne", AFG_2 = "Collines", AFG_3 = "Desert", AFG_4 = "Collines", AFG_5 = "Collines", AGO = "Ville",
		AGO_2 = "Plaine", AGO_3 = "Plaine", AGO_4 = "Plaine", AGO_5 = "Plaine", AGO_6 = "Plaine", ALB = "Ville",
		ALB_2 = "Collines", ARE = "Ville", ARG = "Ville", ARG_10 = "Plaine", ARG_11 = "Plaine", ARG_2 = "Montagne",
		ARG_3 = "Collines", ARG_4 = "Plaine", ARG_5 = "Collines", ARG_6 = "Collines", ARG_7 = "Collines", ARG_8 = "Collines",
		ARG_9 = "Plaine", ARM = "Ville", ARM_2 = "Plaine", ATF = "Plaine", AUS = "Ville", AUS_2 = "Desert",
		AUS_3 = "Desert", AUS_4 = "Plaine", AUS_5 = "Plaine", AUS_6 = "Desert", AUS_7 = "Collines", AUT = "Ville",
		AUT_2 = "Montagne", AUT_3 = "Montagne", AZE = "Montagne", AZE_2 = "Collines", BDI = "Ville", BEL = "Ville",
		BEL_2 = "Plaine", BEN = "Ville", BEN_2 = "Plaine", BFA = "Ville", BFA_2 = "Plaine", BFA_3 = "Plaine",
		BGD = "Ville", BGD_2 = "Plaine", BGR = "Ville", BGR_2 = "Plaine", BGR_3 = "Plaine", BGR_4 = "Plaine",
		BHS = "Ville", BHS_2 = "Plaine", BIH = "Ville", BIH_2 = "Collines", BLR = "Ville", BLR_2 = "Marais",
		BLR_3 = "Marais", BLR_4 = "Plaine", BLR_5 = "Plaine", BLZ = "Ville", BMU = "Plaine", BOL = "Ville",
		BOL_2 = "Plaine", BOL_3 = "Plaine", BOL_4 = "Collines", BOL_5 = "Foret", BOL_6 = "Montagne", BOL_7 = "Plaine",
		BRA = "Ville", BRA_10 = "Plaine", BRA_11 = "Foret", BRA_12 = "Plaine", BRA_13 = "Plaine", BRA_14 = "Plaine",
		BRA_15 = "Plaine", BRA_16 = "Foret", BRA_17 = "Foret", BRA_18 = "Plaine", BRA_19 = "Foret", BRA_2 = "Foret",
		BRA_3 = "Foret", BRA_4 = "Foret", BRA_5 = "Plaine", BRA_6 = "Plaine", BRA_7 = "Plaine", BRA_8 = "Plaine",
		BRA_9 = "Marais", BRN = "Ville", BTN = "Montagne", BWA = "Ville", BWA_2 = "Plaine", BWA_3 = "Desert",
		BWA_4 = "Desert", CAF = "Ville", CAF_2 = "Plaine", CAF_3 = "Plaine", CAF_4 = "Plaine", CAN = "Marais",
		CAN_10 = "Plaine", CAN_11 = "Plaine", CAN_2 = "Foret", CAN_3 = "Foret", CAN_4 = "Foret", CAN_5 = "Plaine",
		CAN_6 = "Plaine", CAN_7 = "Foret", CAN_8 = "Foret", CAN_9 = "Foret", CHE = "Montagne", CHE_2 = "Montagne",
		CHL = "Montagne", CHL_2 = "Montagne", CHL_3 = "Montagne", CHL_4 = "Montagne", CHL_5 = "Montagne", CHL_6 = "Montagne",
		CHN = "Ville", CHN_10 = "Plaine", CHN_11 = "Plaine", CHN_12 = "Plaine", CHN_13 = "Plaine", CHN_14 = "Collines",
		CHN_15 = "Collines", CHN_16 = "Plaine", CHN_17 = "Plaine", CHN_18 = "Collines", CHN_19 = "Collines", CHN_2 = "Plaine",
		CHN_20 = "Plaine", CHN_3 = "Plaine", CHN_4 = "Plaine", CHN_5 = "Plaine", CHN_6 = "Plaine", CHN_7 = "Plaine",
		CHN_8 = "Plaine", CHN_9 = "Plaine", CIV = "Ville", CIV_2 = "Foret", CIV_3 = "Plaine", CMR = "Ville",
		CMR_2 = "Foret", CMR_3 = "Plaine", CMR_4 = "Plaine", COD = "Ville", COD_2 = "Foret", COD_3 = "Foret",
		COD_4 = "Foret", COD_5 = "Plaine", COD_6 = "Foret", COD_7 = "Foret", COD_8 = "Foret", COG = "Ville",
		COG_2 = "Foret", COG_3 = "Foret", COL = "Montagne", COL_2 = "Foret", COL_3 = "Montagne", COL_4 = "Montagne",
		COL_5 = "Plaine", COL_6 = "Foret", COL_7 = "Foret", CRI = "Ville", CUB = "Ville", CUB_2 = "Plaine",
		CYP = "Ville", CZE = "Ville", CZE_2 = "Plaine", CZE_3 = "Collines", DEU = "Ville", DEU_2 = "Plaine",
		DEU_3 = "Plaine", DEU_4 = "Plaine", DEU_5 = "Plaine", DEU_6 = "Plaine", DEU_7 = "Plaine", DJI = "Ville",
		DNK = "Ville", DNK_2 = "Plaine", DOM = "Ville", DZA = "Montagne", DZA_2 = "Desert", DZA_3 = "Desert",
		DZA_4 = "Montagne", DZA_5 = "Desert", DZA_6 = "Plaine", DZA_7 = "Desert", DZA_8 = "Desert", ECU = "Montagne",
		ECU_2 = "Plaine", ECU_3 = "Montagne", EGY = "Ville", EGY_2 = "Desert", EGY_3 = "Desert", EGY_4 = "Plaine",
		EGY_5 = "Desert", EGY_6 = "Desert", ERI = "Ville", ERI_2 = "Desert", ESP = "Ville", ESP_2 = "Plaine",
		ESP_3 = "Collines", ESP_4 = "Montagne", ESP_5 = "Montagne", ESP_6 = "Plaine", ESP_7 = "Plaine", ESP_8 = "Desert",
		EST = "Ville", EST_2 = "Foret", ETH = "Ville", ETH_2 = "Plaine", ETH_3 = "Montagne", ETH_4 = "Plaine",
		ETH_5 = "Collines", ETH_6 = "Desert", FIN = "Ville", FIN_2 = "Foret", FIN_3 = "Plaine", FIN_4 = "Foret",
		FIN_5 = "Foret", FIN_6 = "Foret", FJI = "Ville", FJI_2 = "Plaine", FLK = "Plaine", FRA = "Ville",
		FRA_2 = "Collines", FRA_3 = "Plaine", FRA_4 = "Plaine", FRA_5 = "Plaine", FRA_6 = "Plaine", FRA_7 = "Collines",
		FRA_8 = "Montagne", GAB = "Ville", GAB_2 = "Foret", GAB_3 = "Foret", GBR = "Ville", GBR_2 = "Plaine",
		GBR_3 = "Plaine", GBR_4 = "Plaine", GBR_5 = "Plaine", GEO = "Montagne", GEO_2 = "Montagne", GEO_3 = "Montagne",
		GHA = "Ville", GHA_2 = "Foret", GHA_3 = "Plaine", GIN = "Ville", GIN_2 = "Plaine", GIN_3 = "Plaine",
		GMB = "Ville", GNB = "Ville", GNQ = "Ville", GRC = "Ville", GRC_2 = "Plaine", GRC_3 = "Plaine",
		GRC_4 = "Plaine", GRL = "Plaine", GTM = "Ville", GTM_2 = "Plaine", GUF = "Foret", GUY = "Ville",
		GUY_2 = "Foret", GUY_3 = "Plaine", HND = "Ville", HND_2 = "Plaine", HRV = "Ville", HRV_2 = "Collines",
		HRV_3 = "Collines", HTI = "Ville", HUN = "Ville", HUN_2 = "Plaine", HUN_3 = "Plaine", IDN = "Ville",
		IDN_2 = "Foret", IDN_3 = "Foret", IDN_4 = "Foret", IDN_5 = "Foret", IDN_6 = "Plaine", IDN_7 = "Foret",
		IDN_8 = "Foret", IDN_9 = "Foret", IND = "Montagne", IND_10 = "Desert", IND_11 = "Plaine", IND_2 = "Plaine",
		IND_3 = "Collines", IND_4 = "Plaine", IND_5 = "Plaine", IND_6 = "Plaine", IND_7 = "Plaine", IND_8 = "Plaine",
		IND_9 = "Plaine", IRL = "Ville", IRL_2 = "Plaine", IRL_3 = "Plaine", IRN = "Montagne", IRN_2 = "Montagne",
		IRN_3 = "Desert", IRN_4 = "Desert", IRN_5 = "Desert", IRN_6 = "Montagne", IRN_7 = "Desert", IRN_8 = "Desert",
		IRQ = "Ville", IRQ_2 = "Desert", IRQ_3 = "Desert", IRQ_4 = "Desert", ISL = "Ville", ISL_2 = "Plaine",
		ISL_3 = "Plaine", ISL_4 = "Plaine", ISR = "Ville", ITA = "Ville", ITA_2 = "Montagne", ITA_3 = "Montagne",
		ITA_4 = "Collines", ITA_5 = "Collines", ITA_6 = "Plaine", JAM = "Ville", JOR = "Ville", JOR_2 = "Plaine",
		JPN = "Ville", JPN_2 = "Plaine", JPN_3 = "Collines", JPN_4 = "Plaine", KAZ = "Ville", KAZ_10 = "Plaine",
		KAZ_11 = "Plaine", KAZ_2 = "Plaine", KAZ_3 = "Plaine", KAZ_4 = "Plaine", KAZ_5 = "Plaine", KAZ_6 = "Plaine",
		KAZ_7 = "Plaine", KAZ_8 = "Plaine", KAZ_9 = "Plaine", KEN = "Ville", KEN_2 = "Plaine", KEN_3 = "Plaine",
		KEN_4 = "Plaine", KGZ = "Montagne", KGZ_2 = "Montagne", KGZ_3 = "Montagne", KHM = "Ville", KHM_2 = "Plaine",
		KHM_3 = "Plaine", KOR = "Ville", KOR_2 = "Plaine", KOS = "Ville", KWT = "Ville", LAO = "Ville",
		LAO_2 = "Plaine", LAO_3 = "Plaine", LBN = "Ville", LBR = "Ville", LBR_2 = "Foret", LBY = "Ville",
		LBY_2 = "Desert", LBY_3 = "Desert", LBY_4 = "Desert", LBY_5 = "Desert", LBY_6 = "Desert", LBY_7 = "Desert",
		LKA = "Ville", LKA_2 = "Plaine", LSO = "Ville", LTU = "Ville", LTU_2 = "Plaine", LTU_3 = "Plaine",
		LUX = "Ville", LVA = "Ville", LVA_2 = "Plaine", LVA_3 = "Plaine", MAR = "Montagne", MAR_2 = "Desert",
		MAR_3 = "Montagne", MAR_4 = "Desert", MDA = "Ville", MDA_2 = "Plaine", MDG = "Ville", MDG_2 = "Plaine",
		MDG_3 = "Plaine", MDG_4 = "Plaine", MEX = "Ville", MEX_2 = "Plaine", MEX_3 = "Collines", MEX_4 = "Collines",
		MEX_5 = "Montagne", MEX_6 = "Collines", MEX_7 = "Plaine", MEX_8 = "Desert", MEX_9 = "Collines", MKD = "Ville",
		MKD_2 = "Plaine", MLI = "Ville", MLI_2 = "Desert", MLI_3 = "Plaine", MLI_4 = "Desert", MLI_5 = "Plaine",
		MLI_6 = "Desert", MLT = "Ville", MMR = "Ville", MMR_2 = "Plaine", MMR_3 = "Plaine", MMR_4 = "Plaine",
		MMR_5 = "Plaine", MNE = "Ville", MNG = "Ville", MNG_2 = "Desert", MNG_3 = "Plaine", MNG_4 = "Desert",
		MNG_5 = "Collines", MNG_6 = "Montagne", MNG_7 = "Plaine", MNG_8 = "Desert", MOZ = "Ville", MOZ_2 = "Plaine",
		MOZ_3 = "Plaine", MOZ_4 = "Plaine", MOZ_5 = "Plaine", MRT = "Ville", MRT_2 = "Desert", MRT_3 = "Desert",
		MRT_4 = "Desert", MRT_5 = "Desert", MRT_6 = "Desert", MWI = "Ville", MWI_2 = "Plaine", MYS = "Ville",
		MYS_2 = "Foret", MYS_3 = "Foret", MYS_4 = "Foret", NAM = "Ville", NAM_2 = "Desert", NAM_3 = "Desert",
		NAM_4 = "Desert", NAM_5 = "Desert", NCL = "Plaine", NER = "Ville", NER_2 = "Desert", NER_3 = "Desert",
		NER_4 = "Plaine", NER_5 = "Plaine", NER_6 = "Plaine", NGA = "Ville", NGA_2 = "Plaine", NGA_3 = "Plaine",
		NGA_4 = "Plaine", NGA_5 = "Plaine", NIC = "Ville", NIC_2 = "Plaine", NLD = "Ville", NLD_2 = "Plaine",
		NOR = "Ville", NOR_2 = "Plaine", NOR_3 = "Montagne", NOR_4 = "Montagne", NOR_5 = "Collines", NOR_6 = "Plaine",
		NOR_7 = "Collines", NPL = "Montagne", NPL_2 = "Montagne", NZL = "Ville", NZL_2 = "Montagne", OMN = "Ville",
		OMN_2 = "Desert", OMN_3 = "Desert", PAK = "Ville", PAK_2 = "Desert", PAK_3 = "Montagne", PAK_4 = "Montagne",
		PAK_5 = "Desert", PAK_6 = "Plaine", PAN = "Ville", PAN_2 = "Plaine", PER = "Montagne", PER_2 = "Montagne",
		PER_3 = "Foret", PER_4 = "Foret", PER_5 = "Montagne", PER_6 = "Montagne", PER_7 = "Foret", PHL = "Ville",
		PHL_2 = "Plaine", PHL_3 = "Plaine", PHL_4 = "Plaine", PNG = "Ville", PNG_2 = "Foret", PNG_3 = "Foret",
		PNG_4 = "Foret", POL = "Ville", POL_2 = "Plaine", POL_3 = "Collines", POL_4 = "Plaine", POL_5 = "Plaine",
		POL_6 = "Plaine", PRI = "Plaine", PRK = "Ville", PRK_2 = "Plaine", PRT = "Ville", PRT_2 = "Plaine",
		PRT_3 = "Plaine", PRY = "Ville", PRY_2 = "Plaine", PRY_3 = "Plaine", PRY_4 = "Plaine", PSE = "Ville",
		QAT = "Ville", ROU = "Ville", ROU_2 = "Collines", ROU_3 = "Collines", ROU_4 = "Collines", ROU_5 = "Plaine",
		RUS = "Ville", RUS_10 = "Plaine", RUS_11 = "Plaine", RUS_12 = "Foret", RUS_13 = "Foret", RUS_14 = "Plaine",
		RUS_15 = "Plaine", RUS_16 = "Plaine", RUS_17 = "Plaine", RUS_18 = "Plaine", RUS_19 = "Foret", RUS_2 = "Collines",
		RUS_20 = "Plaine", RUS_21 = "Foret", RUS_22 = "Marais", RUS_23 = "Plaine", RUS_24 = "Plaine", RUS_25 = "Foret",
		RUS_3 = "Plaine", RUS_4 = "Foret", RUS_5 = "Collines", RUS_6 = "Foret", RUS_7 = "Plaine", RUS_8 = "Foret",
		RUS_9 = "Plaine", RWA = "Ville", SAU = "Ville", SAU_2 = "Desert", SAU_3 = "Desert", SAU_4 = "Desert",
		SAU_5 = "Desert", SAU_6 = "Desert", SAU_7 = "Desert", SAU_8 = "Desert", SDN = "Ville", SDN_2 = "Plaine",
		SDN_3 = "Desert", SDN_4 = "Plaine", SDN_5 = "Plaine", SDN_6 = "Plaine", SDN_7 = "Desert", SDN_8 = "Desert",
		SEN = "Ville", SEN_2 = "Plaine", SLB = "Ville", SLE = "Ville", SLV = "Ville", SOM = "Ville",
		SOM_2 = "Plaine", SOM_3 = "Plaine", SOM_4 = "Desert", SRB = "Ville", SRB_2 = "Plaine", SRB_3 = "Plaine",
		SSD = "Ville", SSD_2 = "Plaine", SSD_3 = "Marais", SSD_4 = "Marais", SUR = "Ville", SUR_2 = "Foret",
		SVK = "Ville", SVK_2 = "Collines", SVN = "Montagne", SVN_2 = "Plaine", SWE = "Ville", SWE_2 = "Foret",
		SWE_3 = "Foret", SWE_4 = "Collines", SWE_5 = "Plaine", SWE_6 = "Foret", SWE_7 = "Foret", SWZ = "Ville",
		SYR = "Ville", SYR_2 = "Plaine", TCD = "Ville", TCD_2 = "Plaine", TCD_3 = "Desert", TCD_4 = "Desert",
		TCD_5 = "Plaine", TCD_6 = "Plaine", TGO = "Ville", THA = "Ville", THA_2 = "Plaine", THA_3 = "Plaine",
		THA_4 = "Plaine", THA_5 = "Plaine", TJK = "Ville", TJK_2 = "Montagne", TKM = "Ville", TKM_2 = "Desert",
		TKM_3 = "Desert", TKM_4 = "Desert", TLS = "Ville", TTO = "Ville", TUN = "Ville", TUN_2 = "Plaine",
		TUR = "Ville", TUR_10 = "Collines", TUR_2 = "Montagne", TUR_3 = "Plaine", TUR_4 = "Collines", TUR_5 = "Montagne",
		TUR_6 = "Montagne", TUR_7 = "Collines", TUR_8 = "Montagne", TUR_9 = "Collines", TWN = "Ville", TZA = "Ville",
		TZA_2 = "Plaine", TZA_3 = "Plaine", TZA_4 = "Plaine", TZA_5 = "Plaine", UGA = "Ville", UGA_2 = "Plaine",
		UGA_3 = "Foret", UKR = "Ville", UKR_2 = "Plaine", UKR_3 = "Plaine", UKR_4 = "Collines", UKR_5 = "Plaine",
		UKR_6 = "Marais", UKR_7 = "Plaine", UKR_8 = "Plaine", URY = "Ville", URY_2 = "Plaine", URY_3 = "Plaine",
		USA = "Ville", USA_10 = "Plaine", USA_11 = "Plaine", USA_12 = "Plaine", USA_13 = "Plaine", USA_14 = "Collines",
		USA_15 = "Plaine", USA_16 = "Plaine", USA_17 = "Collines", USA_18 = "Collines", USA_19 = "Plaine", USA_2 = "Collines",
		USA_20 = "Montagne", USA_3 = "Desert", USA_4 = "Collines", USA_5 = "Collines", USA_6 = "Collines", USA_7 = "Plaine",
		USA_8 = "Plaine", USA_9 = "Plaine", UZB = "Ville", UZB_2 = "Desert", UZB_3 = "Desert", UZB_4 = "Desert",
		VEN = "Ville", VEN_2 = "Foret", VEN_3 = "Plaine", VEN_4 = "Plaine", VEN_5 = "Plaine", VEN_6 = "Plaine",
		VNM = "Ville", VNM_2 = "Plaine", VNM_3 = "Plaine", VNM_4 = "Plaine", VUT = "Ville", YEM = "Ville",
		YEM_2 = "Collines", YEM_3 = "Desert", YEM_4 = "Desert", ZAF = "Ville", ZAF_2 = "Plaine", ZAF_3 = "Plaine",
		ZAF_4 = "Collines", ZAF_5 = "Collines", ZAF_6 = "Plaine", ZMB = "Ville", ZMB_2 = "Plaine", ZMB_3 = "Plaine",
		ZMB_4 = "Plaine", ZMB_5 = "Plaine", ZWE = "Ville", ZWE_2 = "Plaine", ZWE_3 = "Plaine",
	} :: { [string]: string },
	rivers = {
		["AFG_2|TJK"] = "Riviere", ["AFG_2|UZB"] = "Riviere", ["AFG|TJK"] = "Riviere", ["AFG|TJK_2"] = "Riviere",
		["AGO_4|ZMB_4"] = "Riviere", ["AGO_5|COD_3"] = "Riviere", ["AGO_5|COD_5"] = "Riviere", ["AGO_6|COD_5"] = "Fleuve",
		["AGO_6|ZMB_3"] = "Riviere", ["AGO_6|ZMB_4"] = "Riviere", ["AGO|COG_3"] = "Fleuve", ["ARG_10|PRY"] = "Fleuve",
		["ARG_2|CHL"] = "Riviere", ["ARG_3|ARG_6"] = "Riviere", ["ARG_6|CHL_6"] = "Riviere", ["ARG_8|CHL_5"] = "Riviere",
		["ARG_9|BRA_12"] = "Fleuve", ["ARG_9|BRA_15"] = "Fleuve", ["ARG_9|PRY"] = "Fleuve", ["ARG_9|URY_3"] = "Fleuve",
		["ARG|ARG_9"] = "Fleuve", ["AUS_2|AUS_7"] = "Riviere", ["AUS|AUS_2"] = "Riviere", ["AUS|AUS_4"] = "Riviere",
		["AUS|AUS_7"] = "Riviere", ["AUT_2|CZE_2"] = "Fleuve", ["AUT_3|CHE"] = "Riviere", ["AUT_3|DEU_2"] = "Fleuve",
		["AUT|CZE_2"] = "Fleuve", ["AUT|SVK"] = "Fleuve", ["BDI|RWA"] = "Fleuve", ["BDI|TZA_2"] = "Fleuve",
		["BEL_2|DEU_7"] = "Riviere", ["BEN_2|NER"] = "Riviere", ["BEN_2|NGA"] = "Riviere", ["BEN_2|NGA_4"] = "Riviere",
		["BEN|NGA"] = "Riviere", ["BFA_2|GHA_3"] = "Riviere", ["BFA_2|MLI"] = "Riviere", ["BFA_2|MLI_5"] = "Riviere",
		["BFA_3|NER"] = "Riviere", ["BFA|BFA_2"] = "Riviere", ["BFA|MLI_2"] = "Riviere", ["BFA|MLI_5"] = "Riviere",
		["BFA|MLI_6"] = "Riviere", ["BFA|NER"] = "Riviere", ["BGD_2|IND_3"] = "Fleuve", ["BGD_2|IND_4"] = "Riviere",
		["BGD|BGD_2"] = "Fleuve", ["BGD|IND_4"] = "Fleuve", ["BGR_2|ROU"] = "Fleuve", ["BGR_2|ROU_5"] = "Fleuve",
		["BGR_4|ROU"] = "Fleuve", ["BLR_3|BLR_4"] = "Riviere", ["BLR_3|RUS"] = "Riviere", ["BLR_3|UKR_7"] = "Riviere",
		["BLR_4|BLR_5"] = "Riviere", ["BLR_4|RUS_6"] = "Riviere", ["BLR_5|LVA_2"] = "Riviere", ["BLR_5|RUS_6"] = "Riviere",
		["BLR|BLR_4"] = "Riviere", ["BOL_2|BOL_7"] = "Riviere", ["BOL_2|BRA_16"] = "Riviere", ["BOL_3|BOL_6"] = "Riviere",
		["BOL_3|BOL_7"] = "Riviere", ["BOL_5|BRA_16"] = "Riviere", ["BOL_7|BRA_9"] = "Fleuve", ["BOL|BOL_3"] = "Riviere",
		["BRA_10|BRA_18"] = "Riviere", ["BRA_10|BRA_9"] = "Riviere", ["BRA_11|BRA_17"] = "Fleuve", ["BRA_11|BRA_19"] = "Riviere",
		["BRA_11|BRA_4"] = "Riviere", ["BRA_11|BRA_7"] = "Riviere", ["BRA_11|GUY_2"] = "Fleuve", ["BRA_11|SUR_2"] = "Fleuve",
		["BRA_12|BRA_9"] = "Fleuve", ["BRA_12|PRY"] = "Fleuve", ["BRA_13|BRA_5"] = "Riviere", ["BRA_16|BRA_2"] = "Riviere",
		["BRA_16|BRA_4"] = "Riviere", ["BRA_16|BRA_8"] = "Riviere", ["BRA_17|BRA_4"] = "Fleuve", ["BRA_17|VEN_2"] = "Riviere",
		["BRA_18|BRA_9"] = "Fleuve", ["BRA_19|BRA_5"] = "Riviere", ["BRA_19|BRA_8"] = "Riviere", ["BRA_2|PER_3"] = "Fleuve",
		["BRA_4|BRA_8"] = "Riviere", ["BRA_4|COL_2"] = "Fleuve", ["BRA_4|COL_6"] = "Fleuve", ["BRA_4|COL_7"] = "Fleuve",
		["BRA_4|PER_3"] = "Fleuve", ["BRA_4|VEN_2"] = "Fleuve", ["BRA_8|BRA_9"] = "Fleuve", ["BRA_9|PRY_2"] = "Fleuve",
		["BRA_9|PRY_4"] = "Fleuve", ["BRA|BRA_19"] = "Riviere", ["BRA|BRA_5"] = "Riviere", ["BRA|BRA_8"] = "Riviere",
		["BTN|CHN_18"] = "Fleuve", ["BTN|IND_3"] = "Fleuve", ["BTN|IND_4"] = "Riviere", ["BWA|ZAF_2"] = "Riviere",
		["CAF_3|COD_2"] = "Fleuve", ["CAF_4|COD_2"] = "Fleuve", ["CAF_4|COD_7"] = "Riviere", ["CAF|COD_2"] = "Fleuve",
		["CAN_10|CAN_11"] = "Fleuve", ["CAN_10|CAN_2"] = "Fleuve", ["CAN_10|CAN_3"] = "Fleuve", ["CAN_10|CAN_6"] = "Riviere",
		["CAN_10|CAN_8"] = "Fleuve", ["CAN_11|USA_2"] = "Riviere", ["CAN_2|CAN_3"] = "Fleuve", ["CAN_2|CAN_8"] = "Riviere",
		["CAN_2|USA_14"] = "Fleuve", ["CAN_3|USA_14"] = "Fleuve", ["CAN_3|USA_18"] = "Riviere", ["CAN_3|USA_2"] = "Riviere",
		["CAN_4|USA_12"] = "Fleuve", ["CAN_4|USA_15"] = "Fleuve", ["CAN_8|USA_14"] = "Fleuve", ["CAN_8|USA_15"] = "Riviere",
		["CAN|USA_12"] = "Fleuve", ["CAN|USA_5"] = "Riviere", ["CHE|CHE_2"] = "Riviere", ["CHE|DEU_2"] = "Fleuve",
		["CHL|CHL_6"] = "Riviere", ["CHN_10|CHN_11"] = "Fleuve", ["CHN_10|CHN_12"] = "Fleuve", ["CHN_10|CHN_16"] = "Riviere",
		["CHN_10|CHN_7"] = "Fleuve", ["CHN_11|CHN_5"] = "Riviere", ["CHN_11|CHN_6"] = "Riviere", ["CHN_12|CHN_2"] = "Fleuve",
		["CHN_12|CHN_5"] = "Riviere", ["CHN_13|RUS_11"] = "Riviere", ["CHN_14|CHN_4"] = "Riviere", ["CHN_15|CHN_4"] = "Riviere",
		["CHN_16|CHN_17"] = "Riviere", ["CHN_16|CHN_4"] = "Riviere", ["CHN_17|CHN_18"] = "Fleuve", ["CHN_17|CHN_20"] = "Fleuve",
		["CHN_17|CHN_7"] = "Fleuve", ["CHN_18|CHN_20"] = "Fleuve", ["CHN_18|IND"] = "Riviere", ["CHN_18|IND_3"] = "Fleuve",
		["CHN_18|IND_4"] = "Fleuve", ["CHN_18|MMR_2"] = "Fleuve", ["CHN_18|NPL"] = "Fleuve", ["CHN_18|NPL_2"] = "Fleuve",
		["CHN_19|CHN_4"] = "Riviere", ["CHN_19|IND"] = "Riviere", ["CHN_19|KGZ"] = "Riviere", ["CHN_19|RUS_2"] = "Fleuve",
		["CHN_20|CHN_6"] = "Riviere", ["CHN_20|CHN_7"] = "Riviere", ["CHN_20|LAO_3"] = "Fleuve", ["CHN_20|MMR"] = "Fleuve",
		["CHN_20|MMR_2"] = "Fleuve", ["CHN_2|CHN_3"] = "Fleuve", ["CHN_3|CHN_5"] = "Riviere", ["CHN_4|MNG_5"] = "Riviere",
		["CHN_5|CHN_6"] = "Riviere", ["CHN_6|CHN_7"] = "Riviere", ["CHN_9|RUS_11"] = "Riviere", ["CHN_9|RUS_23"] = "Riviere",
		["CHN_9|RUS_3"] = "Riviere", ["CHN|CHN_10"] = "Riviere", ["CHN|CHN_2"] = "Riviere", ["CIV_3|GHA_3"] = "Riviere",
		["CMR_3|NGA_2"] = "Riviere", ["CMR_3|NGA_5"] = "Riviere", ["CMR_3|TCD_5"] = "Riviere", ["CMR_4|NGA_5"] = "Riviere",
		["COD_2|COD_7"] = "Fleuve", ["COD_2|COG"] = "Fleuve", ["COD_2|COG_2"] = "Fleuve", ["COD_4|COD_6"] = "Fleuve",
		["COD_4|COD_7"] = "Fleuve", ["COD_5|COD_6"] = "Fleuve", ["COD_5|COD_8"] = "Fleuve", ["COD_5|TZA_3"] = "Fleuve",
		["COD_5|ZMB"] = "Fleuve", ["COD_5|ZMB_2"] = "Fleuve", ["COD_5|ZMB_3"] = "Fleuve", ["COD_5|ZMB_5"] = "Fleuve",
		["COD_7|SSD"] = "Fleuve", ["COD_7|SSD_2"] = "Riviere", ["COD_7|UGA_2"] = "Fleuve", ["COD|COD_2"] = "Riviere",
		["COD|COD_3"] = "Riviere", ["COD|COG"] = "Fleuve", ["COD|COG_3"] = "Fleuve", ["COL_2|COL_4"] = "Riviere",
		["COL_2|COL_6"] = "Riviere", ["COL_3|COL_5"] = "Riviere", ["COL_4|PER_3"] = "Riviere", ["COL_7|VEN_5"] = "Riviere",
		["COL|COL_3"] = "Riviere", ["COL|COL_5"] = "Riviere", ["COL|COL_6"] = "Riviere", ["CRI|NIC"] = "Riviere",
		["CZE_2|DEU_4"] = "Fleuve", ["CZE_3|POL_5"] = "Riviere", ["CZE|DEU"] = "Riviere", ["CZE|DEU_4"] = "Fleuve",
		["CZE|POL_2"] = "Riviere", ["DEU_2|DEU_4"] = "Fleuve", ["DEU_2|DEU_5"] = "Riviere", ["DEU_2|FRA_5"] = "Riviere",
		["DEU_3|DEU_5"] = "Riviere", ["DEU_3|DEU_6"] = "Riviere", ["DEU_4|DEU_5"] = "Fleuve", ["DEU_5|DEU_7"] = "Riviere",
		["DEU_6|POL_4"] = "Riviere", ["DEU_7|NLD_2"] = "Riviere", ["DEU|DEU_3"] = "Riviere", ["DEU|DEU_4"] = "Fleuve",
		["DEU|DEU_5"] = "Riviere", ["DEU|POL_4"] = "Riviere", ["ECU_3|PER_6"] = "Riviere", ["EGY_2|EGY_4"] = "Fleuve",
		["EGY_4|SDN"] = "Fleuve", ["EGY_4|SDN_8"] = "Fleuve", ["EGY|EGY_2"] = "Fleuve", ["EGY|EGY_3"] = "Fleuve",
		["ESP_3|ESP_5"] = "Riviere", ["ESP_3|FRA_6"] = "Riviere", ["ESP_3|FRA_7"] = "Riviere", ["ESP_4|FRA_6"] = "Riviere",
		["ESP_5|ESP_6"] = "Riviere", ["ESP_7|PRT_2"] = "Riviere", ["ESP|ESP_4"] = "Riviere", ["ETH_3|ETH_4"] = "Riviere",
		["ETH_4|SSD_3"] = "Riviere", ["ETH|ETH_4"] = "Riviere", ["FIN_3|RUS_6"] = "Riviere", ["FIN_4|RUS_6"] = "Riviere",
		["FRA_2|FRA_4"] = "Riviere", ["FRA_2|FRA_6"] = "Riviere", ["FRA_2|FRA_7"] = "Riviere", ["FRA_3|FRA_4"] = "Riviere",
		["FRA_4|FRA_6"] = "Riviere", ["FRA|FRA_3"] = "Riviere", ["FRA|FRA_4"] = "Riviere", ["GIN_2|MLI_3"] = "Riviere",
		["GIN_3|MLI_3"] = "Riviere", ["GIN|GIN_2"] = "Riviere", ["GIN|MLI_3"] = "Riviere", ["GTM|GTM_2"] = "Riviere",
		["GTM|MEX_7"] = "Riviere", ["GUY|VEN_3"] = "Riviere", ["HRV|HUN_3"] = "Fleuve", ["HUN_3|SRB"] = "Fleuve",
		["HUN|HUN_2"] = "Fleuve", ["HUN|HUN_3"] = "Fleuve", ["HUN|SVK"] = "Fleuve", ["IND_10|IND_11"] = "Riviere",
		["IND_10|IND_8"] = "Riviere", ["IND_11|IND_4"] = "Riviere", ["IND_11|IND_7"] = "Riviere", ["IND_11|IND_9"] = "Riviere",
		["IND_2|IND_9"] = "Riviere", ["IND_3|IND_4"] = "Fleuve", ["IND_4|NPL"] = "Riviere", ["IND_7|IND_8"] = "Riviere",
		["IND_8|IND_9"] = "Riviere", ["IND|IND_11"] = "Riviere", ["IND|NPL_2"] = "Riviere", ["IND|PAK_3"] = "Riviere",
		["IND|PAK_4"] = "Riviere", ["IRN_3|IRQ_3"] = "Riviere", ["IRN|IRQ_3"] = "Riviere", ["IRN|IRQ_4"] = "Riviere",
		["IRQ_2|IRQ_4"] = "Riviere", ["IRQ_2|SYR_2"] = "Riviere", ["IRQ_3|IRQ_4"] = "Riviere", ["IRQ_4|SAU_3"] = "Riviere",
		["IRQ|IRQ_2"] = "Riviere", ["IRQ|IRQ_4"] = "Riviere", ["IRQ|SYR_2"] = "Riviere", ["KAZ_10|KAZ_6"] = "Riviere",
		["KAZ_11|RUS_2"] = "Fleuve", ["KAZ_11|RUS_22"] = "Fleuve", ["KAZ_3|KAZ_6"] = "Riviere", ["KAZ_3|KAZ_9"] = "Riviere",
		["KAZ_3|RUS_5"] = "Riviere", ["KAZ_4|KAZ_9"] = "Riviere", ["KAZ_4|UZB"] = "Riviere", ["KAZ_4|UZB_4"] = "Riviere",
		["KAZ_5|KAZ_9"] = "Riviere", ["KAZ_6|RUS_24"] = "Riviere", ["KAZ_6|RUS_5"] = "Riviere", ["KAZ_7|RUS_2"] = "Fleuve",
		["KAZ_8|RUS_5"] = "Riviere", ["KAZ_9|UZB_3"] = "Riviere", ["KGZ_2|KGZ_3"] = "Riviere", ["KGZ_2|UZB"] = "Riviere",
		["KGZ|KGZ_3"] = "Riviere", ["KHM_2|KHM_3"] = "Fleuve", ["KHM_3|LAO_2"] = "Fleuve", ["KHM|KHM_2"] = "Fleuve",
		["KHM|VNM_4"] = "Fleuve", ["LAO_2|THA_2"] = "Fleuve", ["LAO_3|MMR"] = "Fleuve", ["LAO_3|THA"] = "Fleuve",
		["LAO_3|THA_2"] = "Fleuve", ["LAO_3|THA_3"] = "Fleuve", ["LAO|LAO_2"] = "Fleuve", ["LAO|LAO_3"] = "Fleuve",
		["LAO|THA_2"] = "Fleuve", ["LBN|SYR_2"] = "Riviere", ["LSO|ZAF_4"] = "Riviere", ["LSO|ZAF_5"] = "Riviere",
		["LTU|LVA_2"] = "Riviere", ["LVA|LVA_2"] = "Riviere", ["MEX_2|USA_3"] = "Riviere", ["MEX_3|USA_17"] = "Riviere",
		["MEX_3|USA_19"] = "Riviere", ["MEX_4|USA_19"] = "Riviere", ["MEX_9|USA_19"] = "Riviere", ["MLI_3|SEN_2"] = "Riviere",
		["MLI_5|MLI_6"] = "Riviere", ["MLI|MLI_3"] = "Riviere", ["MLI|MLI_5"] = "Riviere", ["MLI|MLI_6"] = "Riviere",
		["MLI|MRT_3"] = "Riviere", ["MLI|MRT_4"] = "Riviere", ["MMR_3|MMR_5"] = "Fleuve", ["MMR_5|THA_3"] = "Riviere",
		["MMR_5|THA_4"] = "Riviere", ["MMR|MMR_2"] = "Fleuve", ["MMR|MMR_3"] = "Fleuve", ["MMR|MMR_4"] = "Fleuve",
		["MMR|THA_3"] = "Riviere", ["MNG_7|RUS_2"] = "Fleuve", ["MNG_7|RUS_8"] = "Fleuve", ["MNG|RUS_8"] = "Fleuve",
		["MOZ_4|MOZ_5"] = "Riviere", ["MOZ_4|MWI"] = "Riviere", ["MOZ_4|ZMB"] = "Riviere", ["MOZ_4|ZMB_2"] = "Riviere",
		["MOZ_5|MWI"] = "Riviere", ["MRT_4|SEN"] = "Riviere", ["MRT_4|SEN_2"] = "Riviere", ["MRT|SEN"] = "Riviere",
		["NAM_2|ZAF_2"] = "Riviere", ["NAM_5|ZMB"] = "Riviere", ["NAM_5|ZMB_4"] = "Riviere", ["NAM|ZAF_2"] = "Riviere",
		["NGA|NGA_3"] = "Riviere", ["NGA|NGA_4"] = "Riviere", ["NGA|NGA_5"] = "Riviere", ["NLD|NLD_2"] = "Riviere",
		["NOR_2|RUS_6"] = "Riviere", ["PAK_2|PAK_5"] = "Riviere", ["PAK_3|PAK_4"] = "Riviere", ["PAK|PAK_2"] = "Riviere",
		["PAK|PAK_4"] = "Riviere", ["PAK|PAK_6"] = "Riviere", ["PER_2|PER_4"] = "Fleuve", ["PER_2|PER_5"] = "Fleuve",
		["PER_2|PER_7"] = "Fleuve", ["PER_3|PER_6"] = "Riviere", ["PER_3|PER_7"] = "Fleuve", ["PER|PER_3"] = "Fleuve",
		["PER|PER_6"] = "Riviere", ["PER|PER_7"] = "Fleuve", ["POL_2|POL_4"] = "Riviere", ["POL_2|POL_5"] = "Riviere",
		["POL_3|POL_5"] = "Riviere", ["POL_3|POL_6"] = "Riviere", ["POL_4|RUS_9"] = "Riviere", ["POL_5|SVK"] = "Riviere",
		["POL|POL_3"] = "Riviere", ["POL|POL_4"] = "Riviere", ["POL|POL_5"] = "Riviere", ["PRK_2|RUS_11"] = "Riviere",
		["PRT|PRT_2"] = "Riviere", ["PRY|PRY_4"] = "Fleuve", ["ROU_4|SRB"] = "Fleuve", ["ROU_4|SRB_3"] = "Fleuve",
		["ROU_5|UKR_5"] = "Fleuve", ["ROU|SRB_3"] = "Fleuve", ["RUS_11|RUS_16"] = "Riviere", ["RUS_11|RUS_17"] = "Fleuve",
		["RUS_12|RUS_14"] = "Riviere", ["RUS_12|RUS_15"] = "Fleuve", ["RUS_12|RUS_21"] = "Fleuve", ["RUS_12|RUS_22"] = "Fleuve",
		["RUS_12|RUS_7"] = "Fleuve", ["RUS_13|RUS_14"] = "Riviere", ["RUS_13|RUS_24"] = "Riviere", ["RUS_13|RUS_4"] = "Riviere",
		["RUS_14|RUS_19"] = "Riviere", ["RUS_14|RUS_7"] = "Fleuve", ["RUS_15|RUS_2"] = "Riviere", ["RUS_15|RUS_22"] = "Riviere",
		["RUS_15|RUS_7"] = "Riviere", ["RUS_15|RUS_8"] = "Fleuve", ["RUS_16|RUS_17"] = "Fleuve", ["RUS_17|RUS_20"] = "Fleuve",
		["RUS_17|RUS_23"] = "Fleuve", ["RUS_17|RUS_3"] = "Fleuve", ["RUS_17|RUS_8"] = "Fleuve", ["RUS_19|RUS_21"] = "Riviere",
		["RUS_21|RUS_22"] = "Fleuve", ["RUS_21|RUS_5"] = "Riviere", ["RUS_23|RUS_3"] = "Riviere", ["RUS_23|RUS_8"] = "Fleuve",
		["RUS_24|RUS_25"] = "Riviere", ["RUS_25|RUS_4"] = "Riviere", ["RUS_25|RUS_6"] = "Riviere", ["RUS_2|RUS_22"] = "Riviere",
		["RUS_2|RUS_8"] = "Fleuve", ["RUS_4|RUS_6"] = "Riviere", ["RUS|RUS_25"] = "Riviere", ["RUS|RUS_6"] = "Riviere",
		["RWA|TZA_2"] = "Fleuve", ["SDN_2|SDN_5"] = "Fleuve", ["SDN_2|SDN_6"] = "Fleuve", ["SDN_2|SSD_3"] = "Riviere",
		["SDN_6|SSD_3"] = "Fleuve", ["SDN|SDN_2"] = "Fleuve", ["SDN|SDN_5"] = "Fleuve", ["SDN|SDN_7"] = "Fleuve",
		["SDN|SDN_8"] = "Fleuve", ["SSD_3|SSD_4"] = "Fleuve", ["SSD|SSD_2"] = "Fleuve", ["SSD|SSD_4"] = "Fleuve",
		["SYR_2|TUR_10"] = "Riviere", ["SYR_2|TUR_5"] = "Riviere", ["SYR_2|TUR_8"] = "Riviere", ["SYR|SYR_2"] = "Riviere",
		["TJK|TJK_2"] = "Riviere", ["TKM_3|UZB"] = "Riviere", ["TKM_3|UZB_2"] = "Riviere", ["TUR_4|TUR_8"] = "Riviere",
		["TUR_5|TUR_8"] = "Riviere", ["TZA_2|UGA_3"] = "Fleuve", ["UGA|UGA_2"] = "Fleuve", ["UKR_2|UKR_5"] = "Riviere",
		["UKR_2|UKR_8"] = "Riviere", ["UKR|UKR_7"] = "Riviere", ["USA_10|USA_13"] = "Riviere", ["USA_10|USA_15"] = "Riviere",
		["USA_10|USA_6"] = "Riviere", ["USA_11|USA_12"] = "Fleuve", ["USA_11|USA_5"] = "Riviere", ["USA_12|USA_13"] = "Fleuve",
		["USA_12|USA_9"] = "Fleuve", ["USA_13|USA_15"] = "Riviere", ["USA_13|USA_5"] = "Fleuve", ["USA_13|USA_7"] = "Fleuve",
		["USA_13|USA_9"] = "Fleuve", ["USA_14|USA_18"] = "Fleuve", ["USA_15|USA_6"] = "Riviere", ["USA_16|USA_3"] = "Riviere",
		["USA_16|USA_6"] = "Riviere", ["USA_17|USA_3"] = "Riviere", ["USA_17|USA_6"] = "Riviere", ["USA_18|USA_20"] = "Riviere",
		["USA_20|USA_6"] = "Riviere", ["USA_3|USA_4"] = "Riviere", ["USA_5|USA_9"] = "Riviere", ["UZB_2|UZB_3"] = "Riviere",
		["UZB_3|UZB_4"] = "Riviere", ["VEN_2|VEN_5"] = "Riviere", ["VEN_3|VEN_5"] = "Riviere", ["VEN_4|VEN_5"] = "Riviere",
		["VEN|VEN_5"] = "Riviere", ["ZAF_2|ZAF_4"] = "Riviere", ["ZAF_2|ZAF_5"] = "Riviere", ["ZAF_2|ZAF_6"] = "Riviere",
		["ZAF_5|ZAF_6"] = "Riviere",
	} :: { [string]: string },
}

return RegionTerrain
